server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.243.176:8848 #nacos-server地址 注意：这里不要加任何协议（http）

management:
  endpoints:
    web:
      exposure:
        include: "*"
