server:
  port: 8001
  servlet:
    context-path: /

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.243.176:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
  zipkin: #链路追踪web界面
    base-url: http://localhost:9411
  sleuth: #链路追踪采集
    sampler:
      probability: 0.2 #采样率 值介于0-1之间 1表示全部采集

eureka:
  instance:
    prefer-ip-address: true
    instance-id: payment8001 #集群情况下，同一个服务会有多个实例，这里就是指定当前实例的唯一标识（Eureka中可见）
    #lease-renewal-interval-in-seconds: 20 #表示eureka client发送心跳给server端的时间间隔 默认30秒
    #lease-expiration-duration-in-seconds: 30 #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。默认90秒
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml